---
title: Deel jouw Scratch-project
hero_image: images/banner.png
description: Leer hoe je jouw Scratch-projecten online kunt delen
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Share your Scratch project
