---
title: तुमचा Scratch प्रोजेक्ट शेअर करा
hero_image: प्रतिमा / banner.png
description: तुमचा Scratch प्रोजेक्ट ऑनलाइन कसा शेअर करायचा ते शिका
version: 0
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: तुमचा Scratch प्रोजेक्ट शेअर करा
