---
title: Делимся твоим проектом Scratch
hero_image: images/banner.png
description: Узнай, как поделиться онлайн твоим проектом Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Делимся твоим проектом Scratch
