---
title: Podijeli svoj Scratch projekt
hero_image: images/banner.png
description: NauÄi kako podijeliti svoje Scratch projekte na internetu
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - title: Podijeli svoj Scratch projekt
