---
title: Ein Scratch-Projekt teilen
hero_image: images/banner.png
description: Erfahre, wie du deine Scratch-Projekte online teilen kannst
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - title: Ein Scratch-Projekt teilen
