---
title: Compartilhe seu projeto Scratch
hero_image: images/banner.png
description: Aprenda a compartilhar seus projetos Scratch online
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Share your Scratch project
