---
title: Desa el teu projecte Scratch
hero_image: images/banner.png
description: Apreneu a compartir els vostres projectes Scratch en línia
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Comparteix el teu projecte Scratch
