---
title: Nasdílej svůj projekt ve Scratchi
hero_image: images/banner.png
description: Nauč se jak nasdílet svůj projekt ve Scratchi online
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Nasdílej svůj projekt ve Scratchi
