---
title: Comparte tu proyecto Scratch
hero_image: images/banner.png
description: Aprende a compartir tus proyectos Scratch en línea
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - title: Comparte tu proyecto Scratch
