---
title: Udostępnij swój projekt w Scratchu
hero_image: images/banner.png
description: Dowiedz się jak udostępniać swoje projekty wykonane w Scratchu w internecie
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - title: Udostępnij swój projekt w Scratchu
