---
title: Dela ditt Scratch-projekt
hero_image: images/banner.png
description: Lär dig hur du delar dina Scratch-projekt online
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Dela ditt Scratch-projekt
