---
title: Μοιράσου το έργο Scratch
hero_image: images/banner.png
description: Μάθε πώς να μοιράζεσαι διαδικτυακά τα έργα Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Μοιράσου το έργο Scratch
