---
title: Share your Scratch project
hero_image: images/banner.png
description: Learn how to share your Scratch projects online
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Share your Scratch project
