---
title: Partager ton projet Scratch
hero_image: images/banner.png
description: Apprendre à partager tes projets Scratch en ligne
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Introduction
