---
title: Condividi il tuo progetto Scratch
hero_image: images/banner.png
description: Scopri come condividere i tuoi progetti Scratch online
version: 4
listed: false
copyedit: false
last_tested: "2020-06-04"
steps:
  - 
    title: Condividi il tuo progetto Scratch
